### ISSUE TITLE
Test installation for svlint and svls

### ISSUE THREAD

**Issue by UnsignedByte** [cornell-c2s2/c2s2_ip#21]
Ripped from the google doc, everyone should try this and get it working, leave a comment if you have issues/need clarification.

* Install VSCode
* Install `svlint` and `svls`
    * Download [svlint](https://github.com/dalance/svlint/releases) from the latest release (in the `releases` tab)
        * Unzip and add `bin` directory to `PATH`
            * On Windows: Press the windows key and look up "environment variables". You should get a window that looks like this:
![image](https://github.com/cornell-c2s2/c2s2_ip/assets/34429084/c51761b3-9888-4fb4-a475-a2141bf9a165)
            Click `Environment Variables...`, select `Path` (either under `User variables` or `System variables` if you want every user to be able to access it), click `Edit` and add a row containing `path/to/bin`, the path to your bin directory.
            * On MacOS: edit the `~/.bash_profile` file and add `export PATH="path/to/bin:$PATH"` (replace `path/to/bin` with the path to the unzipped `bin` directory).
            * On Linux: edit the `~/.bashrc` file and add `export PATH="path/to/bin:$PATH"` (replace `path/to/bin` with the path to the unzipped `bin` directory.
    * Test that `svlint` was installed by opening a new terminal window and running `svlint`. If you see a response that isn't something like `command not found`, it was installed properly.
    * Download [svls](https://github.com/dalance/svls/releases) from the latest release
* Install the VSCode extension `svls-vscode`

**Comment by jjm469** [comment]
Not doing this due to installation difficulties.
