### ISSUE TITLE
IP_USED created by checking open branches

### ISSUE THREAD

**Issue by UnsignedByte** [cornell-c2s2/c2s2_ip#3]
https://github.com/cornell-c2s2/c2s2_ip/blob/329f40da28e35ae044cc9c6226398c7139504077/Makefile#L21

Correct me if I'm wrong here, but IP_USED looks at open branches to check if the IP already exists, but when branches are merged to main they will automatically be deleted. Instead, we should probably list folders within the `src` directory to check if IP already exists.

**Comment by Aidan-McNay** [comment]
Yup, you're right, that slipped my mind :') - thanks!
